### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by vtifoski** [jamiemill/figma-comments#1]
TypeError: Cannot read property 'replace' of undefined
    at /figma-comments/lib.js:188:43
    at Array.map (<anonymous>)
    at /figma-comments/lib.js:188:32
    at Array.map (<anonymous>)
    at Object.toCSV (/figma-comments/lib.js:188:17)
    at main (/figma-comments/figma-comments-to-tsv.js:13:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by suburbanworrier** [comment]
See the same error
..except I know that I've run the export successfully in the past so I suspect I'm missing some subtle setup locally or my figma file has gained a comment that breaks this script.

**Comment by rlxa** [comment]
![image](https://user-images.githubusercontent.com/31785125/99378422-bea79e80-290a-11eb-81eb-5982ecfbae93.png)
I got me the same issue. I'm no programmer so this even makes less sense to me. Although I'm guessing it's got something to do with how line breaks are being handled? I'm just guessing at this point haha

**Comment by RobPearsonAmido** [comment]
Me too 
![image](https://user-images.githubusercontent.com/65613260/100351641-a824d580-2fe3-11eb-9992-93f89347d2a4.png)

It's possible Figma has changed it's way of recording comment data i.e. the export is broken because the new format doesn't match the script's expected format
